In [20]:
import pandas as pd
import mysql.connector
import os
from dotenv import load_dotenv
import warnings
from sqlalchemy import create_engine

In [3]:
warnings.filterwarnings('ignore')
load_dotenv(override = True)

True

In [7]:
#Kết nối database
def get_db_connection():
    try :
        return mysql.connector.connect(
            host = os.getenv('MYSQL_SERVER'),
            database = os.getenv('MYSQL_DB'),
            user = os.getenv('MYSQL_USER'),
            password = os.getenv('MYSQL_PASS'),
            port = os.getenv('MYSQL_PORT')
        )
    except Exception as e:
        print(f'Connection Error : {e}')
        return None

In [9]:
# 2. Tải dữ liệu vào DataFrame
conn = get_db_connection()
if conn is not None:
    print(" Đang tải dữ liệu từ kho MySQL...")
    
    # Bảng 1: Hóa đơn mua phần mềm (Chi phí)
    df_invoices = pd.read_sql("SELECT * FROM saas_invoices;", conn)
    
    # Bảng 2: Lịch sử sử dụng phần mềm thực tế của nhân viên (Thực tế)
    df_activity = pd.read_sql("SELECT * FROM vw_user_software_activity;", conn)
    
    conn.close()
    print(" Tải dữ liệu thành công!\n")
    
    print(f" Bảng Invoices (Hóa đơn) có: {df_invoices.shape[0]} dòng và {df_invoices.shape[1]} cột.")
    print(f" Bảng Activity (Sử dụng) có: {df_activity.shape[0]} dòng và {df_activity.shape[1]} cột.")

 Đang tải dữ liệu từ kho MySQL...
 Tải dữ liệu thành công!

 Bảng Invoices (Hóa đơn) có: 4 dòng và 6 cột.
 Bảng Activity (Sử dụng) có: 427 dòng và 9 cột.

In [10]:
#check dữ liệu
# Xem 5 dòng đầu tiên của bảng Hóa đơn (Chi phí mua)
print("--- BẢNG HÓA ĐƠN (SAAS_INVOICES) ---")
display(df_invoices.head())

# Xem 5 dòng đầu tiên của bảng Lịch sử sử dụng (Thực tế sử dụng)
print("\n--- BẢNG LỊCH SỬ SỬ DỤNG (USER_ACTIVITY) ---")
display(df_activity.head())

--- BẢNG HÓA ĐƠN (SAAS_INVOICES) ---

,InvoiceID,InvoiceDate,AppID,TotalLicenses,TotalAmount,PaidByDepartment
0,INV-2026-07-001,2026-07-17,NaN,NaN,1500000.0,None
1,INV-202604-CANVA,2026-04-12,4.0,30.0,360.0,Marketing
2,INV-202604-M365,2026-04-05,1.0,150.0,3000.0,IT
3,INV-202604-ZOOM,2026-04-10,2.0,100.0,1500.0,IT

--- BẢNG LỊCH SỬ SỬ DỤNG (USER_ACTIVITY) ---

,EmpID,FullName,Department,Status,AppName,ApprovedStatus,MonthlyCostPerUser,TotalLogins,LastLoginDate
0,1,Employee_1,IT,Active,Microsoft 365,Approved,20.0,25,2026-06-25 08:00:00
1,1,Employee_1,IT,Active,Zoom,Approved,15.0,10,2026-06-29 08:30:00
2,2,Employee_2,IT,Active,Microsoft 365,Approved,20.0,70,2026-06-29 08:00:00
3,2,Employee_2,IT,Active,Zoom,Approved,15.0,15,2026-06-28 08:30:00
4,3,Employee_3,Marketing,Active,Microsoft 365,Approved,20.0,44,2026-06-28 08:00:00

In [11]:
import pandas as pd

# 1. Đếm số lượng người dùng THỰC TẾ cho từng phần mềm (loại bỏ trùng lặp EmpID)
df_actual_usage = df_activity.groupby('AppName')['EmpID'].nunique().reset_index()
df_actual_usage.rename(columns={'EmpID': 'ActiveUsers'}, inplace=True)

# 2. Tạo một từ điển (Dictionary) nhỏ để nối AppID với AppName 
# (Dựa trên dữ liệu từ ảnh của bạn)
app_mapping = {
    1.0: 'Microsoft 365',
    2.0: 'Zoom',
    4.0: 'Canva'
}

# Áp dụng từ điển vào bảng Hóa đơn để có cột AppName
df_invoices['AppName'] = df_invoices['AppID'].map(app_mapping)

# Lọc bỏ dòng lỗi (NaN) đầu tiên trong bảng Hóa đơn nếu có
df_invoices_clean = df_invoices.dropna(subset=['AppID'])

# 3. Gom nhóm số lượng Licenses đã mua theo từng phần mềm
df_licenses_bought = df_invoices_clean.groupby('AppName')['TotalLicenses'].sum().reset_index()

# 4. KẾT NỐI (MERGE) 2 BẢNG ĐỂ SO SÁNH
df_finops_comparison = pd.merge(df_licenses_bought, df_actual_usage, on='AppName', how='left')

# Nếu phần mềm mua về không có ai dùng, Pandas sẽ để là NaN, ta thay bằng 0
df_finops_comparison['ActiveUsers'] = df_finops_comparison['ActiveUsers'].fillna(0)

# 5. Tính toán mức độ lãng phí (Số tài khoản mua thừa)
df_finops_comparison['WastedLicenses'] = df_finops_comparison['TotalLicenses'] - df_finops_comparison['ActiveUsers']

print("=== BÁO CÁO FINOPS: SO SÁNH LƯỢNG MUA VÀ THỰC TẾ SỬ DỤNG ===")
display(df_finops_comparison)

=== BÁO CÁO FINOPS: SO SÁNH LƯỢNG MUA VÀ THỰC TẾ SỬ DỤNG ===

         AppName  TotalLicenses  ActiveUsers  WastedLicenses
0          Canva           30.0          0.0            30.0
1  Microsoft 365          150.0        192.0           -42.0
2           Zoom          100.0        192.0           -92.0

In [12]:
# 1. Lọc riêng dữ liệu của MS 365 và Zoom (những phần mềm bị âm licenses)
anomalies = ['Microsoft 365', 'Zoom']
df_suspects = df_activity[df_activity['AppName'].isin(anomalies)]

# 2. Thống kê số lượng người dùng theo từng phòng ban
department_usage = df_suspects.groupby(['AppName', 'Department'])['EmpID'].nunique().reset_index()
department_usage.rename(columns={'EmpID': 'Users_Count'}, inplace=True)

print("--- PHÂN BỔ NGƯỜI DÙNG VƯỢT MỨC THEO PHÒNG BAN ---")
display(department_usage.sort_values(by=['AppName', 'Users_Count'], ascending=[True, False]))

# 3. Kiểm tra xem có ai lách luật dùng phần mềm không được phê duyệt (Shadow IT) không
df_shadow_it = df_activity[df_activity['ApprovedStatus'] != 'Approved']

print("\n--- DANH SÁCH CẢNH BÁO SHADOW IT (CHƯA ĐƯỢC PHÊ DUYỆT) ---")
if not df_shadow_it.empty:
    display(df_shadow_it[['EmpID', 'FullName', 'Department', 'AppName', 'ApprovedStatus']])
else:
    print("Không phát hiện trạng thái 'Unapproved' trong log hiện tại. Cần kiểm tra chéo (Cross-check) danh sách cấp phát bản quyền.")

--- PHÂN BỔ NGƯỜI DÙNG VƯỢT MỨC THEO PHÒNG BAN ---

         AppName Department  Users_Count
2  Microsoft 365         IT           48
3  Microsoft 365  Marketing           44
4  Microsoft 365      Sales           35
0  Microsoft 365    Finance           34
1  Microsoft 365         HR           31
7           Zoom         IT           48
8           Zoom  Marketing           44
9           Zoom      Sales           35
5           Zoom    Finance           34
6           Zoom         HR           31

--- DANH SÁCH CẢNH BÁO SHADOW IT (CHƯA ĐƯỢC PHÊ DUYỆT) ---

     EmpID      FullName Department    AppName ApprovedStatus
6        3    Employee_3  Marketing  Canva Pro     Unapproved
17       8    Employee_8  Marketing  Canva Pro     Unapproved
36      17   Employee_17  Marketing  Canva Pro     Unapproved
53      25   Employee_25  Marketing  Canva Pro     Unapproved
56      26   Employee_26  Marketing  Canva Pro     Unapproved
71      34   Employee_34  Marketing  Canva Pro     Unapproved
80      38   Employee_38  Marketing  Canva Pro     Unapproved
83      39   Employee_39  Marketing  Canva Pro     Unapproved
96      45   Employee_45  Marketing  Canva Pro     Unapproved
99      46   Employee_46  Marketing  Canva Pro     Unapproved
102     47   Employee_47  Marketing  Canva Pro     Unapproved
105     48   Employee_48  Marketing  Canva Pro     Unapproved
136     63   Employee_63  Marketing  Canva Pro     Unapproved
143     66   Employee_66  Marketing  Canva Pro     Unapproved
154     71   Employee_71  Marketing  Canva Pro     Unapproved
159     74   Employee_74  Marketing  Canva Pro     Unapproved
164     76   Employee_76  Marketing  Canva Pro     Unapproved
187     87   Employee_87  Marketing  Canva Pro     Unapproved
192     89   Employee_89  Marketing  Canva Pro     Unapproved
197     91   Employee_91  Marketing  Canva Pro     Unapproved
212     99   Employee_99  Marketing  Canva Pro     Unapproved
223    104  Employee_104  Marketing  Canva Pro     Unapproved
252    118  Employee_118  Marketing  Canva Pro     Unapproved
261    122  Employee_122  Marketing  Canva Pro     Unapproved
264    123  Employee_123  Marketing  Canva Pro     Unapproved
277    130  Employee_130  Marketing  Canva Pro     Unapproved
280    131  Employee_131  Marketing  Canva Pro     Unapproved
293    137  Employee_137  Marketing  Canva Pro     Unapproved
298    139  Employee_139  Marketing  Canva Pro     Unapproved
321    150  Employee_150  Marketing  Canva Pro     Unapproved
332    155  Employee_155  Marketing  Canva Pro     Unapproved
335    156  Employee_156  Marketing  Canva Pro     Unapproved
362    172  Employee_172  Marketing  Canva Pro     Unapproved
367    174  Employee_174  Marketing  Canva Pro     Unapproved
374    177  Employee_177  Marketing  Canva Pro     Unapproved
377    178  Employee_178  Marketing  Canva Pro     Unapproved
386    182  Employee_182  Marketing  Canva Pro     Unapproved
393    185  Employee_185  Marketing  Canva Pro     Unapproved
398    187  Employee_187  Marketing  Canva Pro     Unapproved
403    189  Employee_189  Marketing  Canva Pro     Unapproved
412    194  Employee_194  Marketing  Canva Pro     Unapproved
417    196  Employee_196  Marketing  Canva Pro     Unapproved
426    200  Employee_200  Marketing  Canva Pro     Unapproved

In [13]:
import os

# 1. Tạo thư mục 'exports' nếu chưa có để chứa file báo cáo
export_dir = '../exports'
if not os.path.exists(export_dir):
    os.makedirs(export_dir)

# 2. Xuất bảng Báo cáo FinOps (So sánh Lãng phí)
finops_path = os.path.join(export_dir, 'finops_wasted_licenses_report.csv')
df_finops_comparison.to_csv(finops_path, index=False)

# 3. Xuất bảng Cảnh báo Shadow IT (Phân bổ phòng ban)
shadow_it_path = os.path.join(export_dir, 'shadow_it_department_warning.csv')
department_usage.to_csv(shadow_it_path, index=False)

print(f" Đã xuất báo cáo thành công vào thư mục: {export_dir}")
print("Tên các file được tạo ra:")
print(f"1. {finops_path}")
print(f"2. {shadow_it_path}")

 Đã xuất báo cáo thành công vào thư mục: ../exports
Tên các file được tạo ra:
1. ../exports\finops_wasted_licenses_report.csv
2. ../exports\shadow_it_department_warning.csv

In [14]:
# --- 1. TÌM NHÂN VIÊN BỊ CỜ ĐỎ (SHADOW IT TRỰC TIẾP) ---
df_red_flag = df_activity[df_activity['ApprovedStatus'] != 'Approved']

print(" DANH SÁCH CỜ ĐỎ: NHÂN VIÊN SỬ DỤNG PHẦN MỀM CHƯA ĐƯỢC PHÊ DUYỆT")
if not df_red_flag.empty:
    display(df_red_flag[['EmpID', 'FullName', 'Department', 'AppName', 'ApprovedStatus']])
else:
    print("-> Hiện tại hệ thống không ghi nhận nhân viên nào có trạng thái 'Unapproved'.\n")


# --- 2. TÌM NHÂN VIÊN BỊ CỜ VÀNG (SỬ DỤNG PHẦN MỀM VƯỢT QUỸ ĐỊNH) ---
# Lấy danh sách nhân viên dùng MS 365 và Zoom, loại bỏ các dòng trùng lặp nếu họ đăng nhập nhiều lần
df_yellow_flag = df_activity[df_activity['AppName'].isin(['Microsoft 365', 'Zoom'])]
df_yellow_flag_unique = df_yellow_flag[['EmpID', 'FullName', 'Department', 'AppName']].drop_duplicates()

print(" DANH SÁCH CỜ VÀNG: NHÂN SỰ ĐANG DÙNG MS 365 & ZOOM (CẦN RÀ SOÁT BẢN QUYỀN)")
display(df_yellow_flag_unique.sort_values(by=['AppName', 'Department', 'EmpID']))

# (Tùy chọn) Xuất danh sách cờ vàng ra file Excel/CSV để gửi cho các Trưởng phòng đối chiếu
yellow_flag_path = os.path.join(export_dir, 'flagged_users_for_audit.csv')
df_yellow_flag_unique.to_csv(yellow_flag_path, index=False)
print(f"\n Đã lưu danh sách cần rà soát vào file: {yellow_flag_path}")

 DANH SÁCH CỜ ĐỎ: NHÂN VIÊN SỬ DỤNG PHẦN MỀM CHƯA ĐƯỢC PHÊ DUYỆT

     EmpID      FullName Department    AppName ApprovedStatus
6        3    Employee_3  Marketing  Canva Pro     Unapproved
17       8    Employee_8  Marketing  Canva Pro     Unapproved
36      17   Employee_17  Marketing  Canva Pro     Unapproved
53      25   Employee_25  Marketing  Canva Pro     Unapproved
56      26   Employee_26  Marketing  Canva Pro     Unapproved
71      34   Employee_34  Marketing  Canva Pro     Unapproved
80      38   Employee_38  Marketing  Canva Pro     Unapproved
83      39   Employee_39  Marketing  Canva Pro     Unapproved
96      45   Employee_45  Marketing  Canva Pro     Unapproved
99      46   Employee_46  Marketing  Canva Pro     Unapproved
102     47   Employee_47  Marketing  Canva Pro     Unapproved
105     48   Employee_48  Marketing  Canva Pro     Unapproved
136     63   Employee_63  Marketing  Canva Pro     Unapproved
143     66   Employee_66  Marketing  Canva Pro     Unapproved
154     71   Employee_71  Marketing  Canva Pro     Unapproved
159     74   Employee_74  Marketing  Canva Pro     Unapproved
164     76   Employee_76  Marketing  Canva Pro     Unapproved
187     87   Employee_87  Marketing  Canva Pro     Unapproved
192     89   Employee_89  Marketing  Canva Pro     Unapproved
197     91   Employee_91  Marketing  Canva Pro     Unapproved
212     99   Employee_99  Marketing  Canva Pro     Unapproved
223    104  Employee_104  Marketing  Canva Pro     Unapproved
252    118  Employee_118  Marketing  Canva Pro     Unapproved
261    122  Employee_122  Marketing  Canva Pro     Unapproved
264    123  Employee_123  Marketing  Canva Pro     Unapproved
277    130  Employee_130  Marketing  Canva Pro     Unapproved
280    131  Employee_131  Marketing  Canva Pro     Unapproved
293    137  Employee_137  Marketing  Canva Pro     Unapproved
298    139  Employee_139  Marketing  Canva Pro     Unapproved
321    150  Employee_150  Marketing  Canva Pro     Unapproved
332    155  Employee_155  Marketing  Canva Pro     Unapproved
335    156  Employee_156  Marketing  Canva Pro     Unapproved
362    172  Employee_172  Marketing  Canva Pro     Unapproved
367    174  Employee_174  Marketing  Canva Pro     Unapproved
374    177  Employee_177  Marketing  Canva Pro     Unapproved
377    178  Employee_178  Marketing  Canva Pro     Unapproved
386    182  Employee_182  Marketing  Canva Pro     Unapproved
393    185  Employee_185  Marketing  Canva Pro     Unapproved
398    187  Employee_187  Marketing  Canva Pro     Unapproved
403    189  Employee_189  Marketing  Canva Pro     Unapproved
412    194  Employee_194  Marketing  Canva Pro     Unapproved
417    196  Employee_196  Marketing  Canva Pro     Unapproved
426    200  Employee_200  Marketing  Canva Pro     Unapproved

 DANH SÁCH CỜ VÀNG: NHÂN SỰ ĐANG DÙNG MS 365 & ZOOM (CẦN RÀ SOÁT BẢN QUYỀN)

     EmpID      FullName Department        AppName
26      13   Employee_13    Finance  Microsoft 365
30      15   Employee_15    Finance  Microsoft 365
37      18   Employee_18    Finance  Microsoft 365
39      19   Employee_19    Finance  Microsoft 365
45      22   Employee_22    Finance  Microsoft 365
..     ...           ...        ...            ...
359    171  Employee_171      Sales           Zoom
364    173  Employee_173      Sales           Zoom
388    183  Employee_183      Sales           Zoom
409    193  Employee_193      Sales           Zoom
421    198  Employee_198      Sales           Zoom

[384 rows x 4 columns]

 Đã lưu danh sách cần rà soát vào file: ../exports\flagged_users_for_audit.csv

In [15]:
# 1. Gom nhóm dữ liệu theo từng nhân viên
df_consolidated = df_yellow_flag_unique.groupby(['EmpID', 'FullName', 'Department']).agg(
    Flagged_Apps=('AppName', lambda x: ', '.join(x)), # Gom tên phần mềm thành 1 chuỗi cách nhau dấu phẩy
    App_Count=('AppName', 'count')                    # Đếm số lượng phần mềm vi phạm
).reset_index()

# 2. Xây dựng hàm đánh giá mức độ rủi ro dựa trên số lượng phần mềm (App_Count)
def evaluate_risk(count):
    if count == 1:
        return "Rủi ro Thấp: Cần bộ phận liên quan xác minh lại nhu cầu sử dụng thực tế."
    elif count == 2:
        return "Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản (Account sharing) liên ứng dụng."
    else:
        return "Rủi ro Cao: Báo động Shadow IT nghiêm trọng, sử dụng trái phép nhiều ứng dụng."

# 3. Tạo cột Ghi chú đánh giá
df_consolidated['Risk_Evaluation'] = df_consolidated['App_Count'].apply(evaluate_risk)

# 4. Sắp xếp danh sách ưu tiên theo số lượng vi phạm giảm dần để xử lý trước
df_consolidated = df_consolidated.sort_values(by='App_Count', ascending=False)

print("--- DANH SÁCH NHÂN VIÊN BỊ CỜ ĐÃ ĐƯỢC GOM GỌN & ĐÁNH GIÁ ---")
display(df_consolidated.head(10))

# 5. Xuất file báo cáo mới đã được tối ưu
optimized_path = os.path.join(export_dir, 'consolidated_flagged_users.csv')
df_consolidated.to_csv(optimized_path, index=False, encoding='utf-8')
print(f"\n✅ Đã xuất báo cáo đánh giá rủi ro thành công: {optimized_path}")

--- DANH SÁCH NHÂN VIÊN BỊ CỜ ĐÃ ĐƯỢC GOM GỌN & ĐÁNH GIÁ ---

,EmpID,FullName,Department,Flagged_Apps,App_Count,Risk_Evaluation
0,1,Employee_1,IT,"Microsoft 365, Zoom",2,Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản ...
1,2,Employee_2,IT,"Microsoft 365, Zoom",2,Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản ...
2,3,Employee_3,Marketing,"Microsoft 365, Zoom",2,Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản ...
3,4,Employee_4,IT,"Microsoft 365, Zoom",2,Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản ...
4,5,Employee_5,HR,"Microsoft 365, Zoom",2,Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản ...
5,6,Employee_6,Sales,"Microsoft 365, Zoom",2,Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản ...
6,7,Employee_7,Sales,"Microsoft 365, Zoom",2,Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản ...
7,8,Employee_8,Marketing,"Microsoft 365, Zoom",2,Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản ...
8,9,Employee_9,HR,"Microsoft 365, Zoom",2,Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản ...
9,10,Employee_10,HR,"Microsoft 365, Zoom",2,Rủi ro Trung bình: Dấu hiệu chia sẻ tài khoản ...

✅ Đã xuất báo cáo đánh giá rủi ro thành công: ../exports\consolidated_flagged_users.csv

In [24]:
# 1. Lấy thông tin từ các biến môi trường mà bạn đã load sẵn qua load_dotenv()
host = os.getenv('MYSQL_SERVER')
database = os.getenv('MYSQL_DB')
user = os.getenv('MYSQL_USER')
password = os.getenv('MYSQL_PASS')
port = os.getenv('MYSQL_PORT')

# 2. Tạo SQLAlchemy Engine, sử dụng chính driver 'mysqlconnector' mà bạn đang dùng
# Cú pháp: mysql+driver://user:pass@host:port/database
connection_string = f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}"
engine = create_engine(connection_string)

try:
    print("Đang đẩy dữ liệu lên MySQL Data Mart...")
    
    # 3. Sử dụng engine để ghi bảng Cảnh báo Shadow IT
       df_consolidated.to_sql(
        name='fact_shadow_it_flags', 
        con=engine, 
        if_exists='replace', 
        index=False
    )
    print(" Đã tạo và đổ dữ liệu thành công vào bảng: fact_shadow_it_flags")

    # 4. Sử dụng engine để ghi bảng Lãng phí FinOps
    df_finops_comparison.to_sql(
        name='fact_finops_waste', 
        con=engine, 
        if_exists='replace', 
        index=False
    )
    print(" Đã tạo và đổ dữ liệu thành công vào bảng: fact_finops_waste")
    
except Exception as e:
    print(f" Lỗi ghi dữ liệu: {e}")

IndentationError: unexpected indent (3913869976.py, line 17)